### ISSUE TITLE
WorkspaceSymbols doesn't work as documented

### ISSUE THREAD

**Issue by astavonin** [gfanto/fzf-lsp.nvim#12]
> Call :WorkspaceSymbols to show all the symbols in the workspace, you can optionally pass the query as an argument to the command

If I call `:WorkspaceSymbols` without arguments next error occurs:

```
Workspace Symbol not found
```
But if I provide something, I can choose from the provided options.

**Comment by gfanto** [comment]
This depends on the implementation of the language server, there are language servers that return every symbol if you pass an empty query, as the language server specification says, others not to return everything, because it can be very slow on large projects, they just don't return anything, so fzf-lsp.vim in case it says `Workspace symbol not found`.

Maybe I can be clearer in the documentation, but it should be what's happening to you.

**Comment by astavonin** [comment]
Thanks for the explanation, I did try with `clangd`.
