### ISSUE TITLE
looks link fzf-lsp doesn't respect g:fzf_preview_window settting

### ISSUE THREAD

**Issue by bryceyang** [gfanto/fzf-lsp.nvim#5]
nvim version:
```shell
NVIM v0.5.0-dev+967-g7afd4526f
Build type: Release
LuaJIT 2.1.0-beta3
```
I got this fzf preview settings in my config: ` let g:fzf_preview_window = ['up:40%', 'ctrl-/'] `, which makes the preview window in the top section of float window.

this is the screenshot when i find a file using fzf.vim, which works as expected:
![image](https://user-images.githubusercontent.com/9302617/103084411-e67cd700-4619-11eb-82ac-c44ea4209fa5.png)

and this is the screenshot when i find references using fzf-lsp:
![image](https://user-images.githubusercontent.com/9302617/103084463-fe545b00-4619-11eb-8ae8-22c21d409d29.png)

How can I make fzf-lsp respects g:fzf_xxx settings?

**Comment by gfanto** [comment]
The problem is that i'm working with just the minimum fzf plugin end not with fzf.vim right now so i do not respect the fzf_preview_window settings, but i can make a fix adding the support with no problems, and in short amount of time.
Now i'm a little bit busy, but i think in few hours from now i'll make the update.

Thank for reporting this, i will never found that, because i usually use the default settings for the window preview

**Comment by gfanto** [comment]
Ok, as i promised you i added the support to the preview window settings.
Run `:PlugUpdate` and should work with your standard configuration.
If you want to have different settings from your default fzf settings (for example i like having symbols to the bottom and files in the center window) just use the `g:fzf_lsp_preview_window` global variable.

**Comment by bryceyang** [comment]
Things works as expected now!  Thx for your help.
